# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informer',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaintManager.InformerOrigin'),
        ),
    ]
