# Generated by Django 2.0.2 on 2018-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='additional_division',
            field=models.ManyToManyField(to='complaintManager.Division'),
        ),
    ]
