# Generated by Django 2.0.3 on 2018-03-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0002_auto_20170522_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='complaintManager.Division'),
        ),
        migrations.AlterField(
            model_name='complaintimages',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaintManager.Log'),
        ),
        migrations.AlterField(
            model_name='informer',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaintManager.InformerOrigin'),
        ),
        migrations.AlterField(
            model_name='log',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
