# Generated by Django 2.0.3 on 2018-03-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0003_auto_20180318_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='complaintManager.Division'),
        ),
    ]
