# Generated by Django 2.0.3 on 2018-03-19 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0006_auto_20180319_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='complaintManager.Division'),
        ),
        migrations.AlterField(
            model_name='complaintimages',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaintManager.Log'),
        ),
    ]
