# Generated by Django 2.0.3 on 2018-03-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0010_auto_20180319_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PU', 'Perawatan Utilitas'), ('PG', 'Perawatan Gedung'), ('OG', 'Operasional dan Kebersihan Gedung')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='complaintManager.SelectedDivision'),
        ),
    ]
