# Generated by Django 2.0.3 on 2018-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintManager', '0012_auto_20180319_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('PU', 'Perawatan Utilitas'), ('PG', 'Perawatan Gedung'), ('OG', 'Operasional dan Kebersihan Gedung'), ('KS', 'Kebersihan dan Pengelolaan Sampah'), ('IA', 'Inventarisasi Aset'), ('PDA', 'Pendayagunaan Aset'), ('PHA', 'Penghapusan Aset'), ('PD', 'Penerimaan dan Distribusi'), ('S', 'Sekretariat')], max_length=10),
        ),
    ]
